pub mod circuit;
pub mod cli;
pub mod config;
pub mod crypto;
pub mod daemon;
pub mod dht;
pub mod error;
pub mod fragment;
pub mod fuzzing;
pub mod grpc;
pub mod handshake;
pub mod integration_tests;
pub mod logging;
pub mod metrics;
pub mod network;
pub mod padding;
pub mod pow;
pub mod protocol;
pub mod rate_limiter;
pub mod routing;
pub mod socks5;
pub mod transport;
pub mod tunnel;

pub const PROTOCOL_VERSION: u8 = 1;
pub const MAX_PACKET_SIZE: usize = 1450;
